### ISSUE TITLE
Windows wave editor

### ISSUE THREAD

**Issue by uselessgames** [stargateaudio/stargate#35] opened 2021-08-08 14:59 UTC
**Describe the bug**
when opening a wav file into the wave editor stargate crashes with error code 3221225477.
DAW doesn't work either, but it doesn't return any errors, it simply shows the thinking wheel and doesn't open (waited 5 minutes)

**To Reproduce**
Open stargate, switch to wave editor, try to open .wav file. 

**Expected behavior**
open wav file with wav editor

**Screenshots**
![Annotation 2021-08-08 164724](https://user-images.githubusercontent.com/66875544/128636323-6eac1c2a-b24e-4154-8d76-39a24e822a1c.jpg)

**Hardware and operating system**
Intel i5 @1.6GHz, 8GB RAM, laptop, x64, Windows 10 Pro

**Additional context**

**Comment by stargateaudio** [comment] 2021-08-08 17:23
This might already be fixed in the latest `main` branch.  I will create another release soon.

**Comment by stargateaudio** [comment] 2021-08-09 06:59
Please upload the log file in `C:\Users\%YOU%\stargate\log\stargate.log` when you get a chance.  I suspect we will see that attempts to use UDP sockets over localhost failed.  Either because of bugs that were recently fixed in the latest `main`, or else maybe this is something like Windows Defender or antivirus deciding that allowing a process to communicate with it's child process over sockets is just too risky.

**Comment by uselessgames** [comment] 2021-08-09 07:54
here is the [stargate.log](https://github.com/stargateaudio/stargate/files/6952817/stargate.log)

**Comment by stargateaudio** [comment] 2021-08-09 15:38
Thanks.  It was not what I thought it was, but there is a stack trace in there that is almost certainly the root cause.

Not sure what it is, or why I never encountered it, but it looks like an easy fix.  I will try to fix it tonight and create a new release.

**Comment by stargateaudio** [comment] 2021-08-10 02:44
There were a handful of errors, I think I fixed all of them except for maybe one, I handled an error that should not be happening (engine sends a NaN value for the playback cursor position to the UI?  I at least logged it now so we can see what it sent).

This is the one I am not sure about:
```
[2021-08-08 16:48:47,442] ERROR sglib\log.py                  : 48 - Traceback (most recent call last):
  File "sgui\wave_edit\__init__.py", line 1109, in on_file_open
  File "sgui\wave_edit\__init__.py", line 1154, in open_file
  File "sglib\models\stargate\project.py", line 446, in get_wav_uid_by_name
  File "sglib\models\stargate\audio_pool.py", line 134, in add_entry
  File "pymarshal\util\pm_assert.py", line 17, in pm_assert
FileExistsError:
```
What makes that one so baffling is that the `get_wav_uid_by_name` checks that `path` is not in `AudioPool.by_path()`, then makes a call to `add_entry`, where the method to add it then asserts that it is not in `by_path`, which fails because the file is in there.  I examined it closely and did not see how this is possible.

If you don't mind sharing a zip of your project folder with me (send it to me privately, don't upload it here, it includes the audio files you loaded), I can try to get to the bottom of why that is happening.

**Comment by stargateaudio** [comment] 2021-08-10 03:55
Oooooh..  Nevermind.  I was able to reproduce that bug in my Windows VM, debugging it right now.  I was mid-way through releasing a new release, I will fix it and re-spin the release.

**Comment by stargateaudio** [comment] 2021-08-10 04:36
Should be fixed now, I am resuming the release, it will be uploaded shortly.

**Comment by stargateaudio** [comment] 2021-08-13 04:40
Pretty sure this is fixed now, I will close the issue.  If you are still having problems, we can reopen this issue or create a new one.

**Closed by stargateaudio** 2021-08-13 04:40 UTC
Labels: bug
