### ISSUE TITLE
fm1 oscillator sustain is too low, even at maximum value

### ISSUE THREAD

**Issue by autumncheney** [stargateaudio/stargate#33] opened 2021-08-03 04:32 UTC
**Describe the bug**
in the fm1 synth, the sustain knob seems to be set to a low volume by default, and turning it all the way up doesn't seem to actually raise the sustain in the envelope all the way

**To Reproduce**

**Expected behavior**
i expect that when the sustain is all the way up and the attack and decay are all the way down, the modulation is loud and steady

**Screenshots**

**Hardware and operating system**

**Additional context**

**Comment by stargateaudio** [comment] 2021-08-04 01:06
The oscillators all have their own envelopes, but there is a `Main` envelope on the `Modulation` tab that modulates volume for all oscillators after they are mixed together.  If the `Main` envelope has a low sustain value, that will override anything the individual oscillator envelopes are doing.

Is the `Main` envelope's sustain also all the way up?  If so, can you give me the name of the preset that exhibits this behavior, or if it is something you created, can you maybe save it to a preset bank and upload it here?

**Comment by autumncheney** [comment] 2021-08-04 01:41
sure, i'll save it

here's a bank with only one preset, just adjust the decay knob on the first oscillator to see what i described
[test.sgp.tar.gz](https://github.com/stargateaudio/stargate/files/6928001/test.sgp.tar.gz)

**Comment by stargateaudio** [comment] 2021-08-04 03:56
Thanks, I am able to reproduce the bug.  Something is definitely amiss there, like maybe that knob is connected to something other than the envelope it is supposed to be connected to.  Have not figured out yet, but I will keep investigating.

**Comment by stargateaudio** [comment] 2021-08-04 04:24
It seems to be that turning up the decay actually makes the overall sound much louder, which should not be the case.  I'm going to write some unit tests for the (D)A(H)DSR envelope to see if I can figure out what's going on here.

**Comment by stargateaudio** [comment] 2021-08-04 05:16
I think this is fixed in the latest code in `main`

**Comment by stargateaudio** [comment] 2021-08-06 04:35
I added some unit tests that confirm that the DAHDSR envelope stays in the expected range during each stage.  I believe all of the bugs are fixed now, thanks for reporting.  If you find any other issues, feel free to re-open this issue or create a new one.

**Closed by stargateaudio** 2021-08-06 04:35 UTC
Labels: bug
